package:
  name: hdf4
  version: "4.2.10"

source:
  fn: hdf-4.2.10.tar.bz2
  url: http://www.hdfgroup.org/ftp/HDF/HDF_Current/src/hdf-4.2.10.tar.bz2
  md5: bf26b3caaf3c0090965c8995578375bd
  sha1: 5163543895728dabb536a0659b3d965d55bccf74
  sha256: 44e9c7f5bdd463c4a01738f44ad4f0ee9c68e3f0cb9872eca160e3fddc8b994c

build:
    number:  1

requirements:
  build:
    - jpeg
    - zlib
  run:
    - jpeg
    - zlib

about:
  home: http://www.hdfgroup.org
  license: BSD-style (http://www.hdfgroup.org/ftp/HDF5/current/src/unpacked/COPYING)
